import { authOption } from "../api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import { redirect } from "next/dist/server/api-utils";
import AppSidebar from "@/components/layout/AppSidebar";
import {Toaster} from 'react-hot-toast'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LinkList",
  description: "Generated by create next app",
};

export default async function AppLayout({ children, ...rest }) {
  const session = await getServerSession(authOption);
  if (!session) {
    return redirect("/");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        <main className="flex min-h-screen">
          <aside className="bg-white w-48 p-4 shadow">
            <div className="rounded-full overflow-hidden aspect-square w-24 mx-auto">
              <Image
                src={session?.user?.image}
                width={256}
                height={256}
                alt={"avatar"}
              />
            </div>
            <div className="text-center">
              <AppSidebar/>
            </div>
          </aside>
          <div className="grow">
            <div className="bg-white m-8 p-4 shadow">
            {children}</div>
            </div>
        </main>
      </body>
    </html>
  );
}
